### ISSUE TITLE
Add Events to key Citrus Lifecycle methods

### ISSUE THREAD

**Issue by Paitum** [DaVikingCode/Citrus-Engine#232]
My specific use-case was to perform an action on a newly instantiated StarlingState that was just added to the state. Unfortunately the initialize() method is called later from within Citrus, and Citrus did not provide me with any facility to register a listener for the completion of the initializer.

``` actionscript
var gameState:StarlingState = new GameState();
state = gameState;
gameState.getBoard().doSomething();
```

In my example, the board would be null because it wasn't initialized yet.

I would recommend to evaluate places within the Citrus lifecycle that implementors would need to listen for.

See [Thomas's Post on Starling Forum](http://forum.starling-framework.org/topic/event-after-a-starlingstate-gets-initialize)

**Comment by gsynuh** [comment]
Closing this issue as SceneManager introduces 

onsceneAdded and onsceneRemoved signals. The first one being dispatched after the scene is added to the display list and initialize() , the second one after destroy() is called and its removal from the display list.

https://github.com/DaVikingCode/Citrus-Engine/blob/1d06a48b47498bfc5ba3a67ad8ca1ed430e6f2e2/src/citrus/core/SceneManager.as#L11
https://github.com/DaVikingCode/Citrus-Engine/blob/1d06a48b47498bfc5ba3a67ad8ca1ed430e6f2e2/src/citrus/core/SceneManager.as#L15
