### ISSUE TITLE
ObjectMakers.FromMovieClip - undefined vars

### ISSUE THREAD

**Issue by gsynuh** [DaVikingCode/Citrus-Engine#253]
In Theory, to avoid undefined vars (classNames, or even params/view and so on when not using components) , gotoAndStop(1); on the movieclip fixes it. Am I right? 
The suggestion here is to force gotoAndStop(1); before parsing the level so we don't have to.

edit : yes, that works. I just had confirmation. This would be safer for everyone, and anyway people shouldn't create their level over many frames so gotoAndStop(1) can only help.

**Comment by creativcheck** [comment]
Great :)
