### ISSUE TITLE
NapePhysicsObject.as - Thought regarding '_shape'

### ISSUE THREAD

**Issue by Snky** [DaVikingCode/Citrus-Engine#255]
I was thinking the other day, wouldn't it better to provide a vector array, instead of assuming the user will only need one shape? 

protected var _vecShape:Vector.< Shape >

You could still keep the getter for shape I guess, but return _vecShape[ 0 ], instead. Just an idea / my preference, but when I look at it from the community point of view, maybe they would make use of this too, and if not they would still be able to call the getter on shape, I just think it's better to assume / get them in the practice of this: one body -> multiple shapes, not: multiple bodies -> one shape( per ).

I've read that connecting bodies as so, with just one shape would make the compound very unstable compared to several shapes in one body. Just a thought, I don't mind bending this all the time if the class ever gets updated. :P I will most likely always be working with multiple shapes, then '_shape' sits there.. all lonely, never assigned.. what a lonely life

--EDIT--
I forgot, maybe if this approach was liked, a shape adder function may be needed?
//create shape replacement
for loop _vecShape.length
body.shapes.add( _vecShape[ i ]

--EDIT2--
Or maybe I'm thinking of a new class, NapePhysicsCompound

Well, still just a thought.

**Comment by gsynuh** [comment]
eheh, just visiting issues, I was going to add a comment but it would've been exactly what you're Edit2 is saying. I would want a special compound object for sure.
