### ISSUE TITLE
modification? - swap 'name / params' parameters around

### ISSUE THREAD

**Issue by Snky** [DaVikingCode/Citrus-Engine#260]
Hopefully this is not just my preference, but I have indeed found it a lot easier after swapping these two parameters in every class around, as you can inside params { name: "........." , ... }, or even per class set a default name like so:

<pre lang="as3">
public function SnkyNape( params:Object = null , name:String = "SnkyNape-blueprint" ){
    super( params , name );

public class o_nape_cog extends SnkyNape {
public function o_nape_cog( params:Object = null , name:String = "o_nape_cog-undefined" ){
    super( params , name );
</pre>

.. on top of the fact you can set the name inside params, I personally feel it's a bit of a burden how much importance name has been given that it's a must to give one to each object as you create them / create classes.

Again only a thought for the community, it doesn't really bother me, but even if this saves like 10 seconds per creating a class I dunno.. I'm a lot more at ease now XD, I can manage up to 50% destruction of Starling and CE >.< it's cool!

After a good little think, I think you'll agree at least, that params has a much greater significance in priority.

Oh p.s., not only have I run out of suggestions, I'm going to stay quiet 'til you guys get some CE projects anyway, otherwise it's just going to pile up, probably end up confusing, what's major/minor/pointless.

**Comment by gsynuh** [comment]
Hi,
I'm making the move to no name argument at all.
I think its useless to even have it... name would be extracted from the params object,
if it doesn't exist there, a default name of citrusObjectInstance_X will be set where X is the citrus object 'unique' ID.

**Comment by gsynuh** [comment]
done as of a29b29e0e1bc39964b413f7a5299e497b756a7ca
