### ISSUE TITLE
StarlingState missing in CEV3-1-10-ALL

### ISSUE THREAD

**Issue by kyle1046** [DaVikingCode/Citrus-Engine#262]
Hey guys

I just started a new project and want to thank you all for the great work you do, with the Citrus Engine, since this is gonna make my life much easier! Much obliged! :+1:

Courtesies aside, I am trying to use the CEV3-1-10-ALL.swc, but if I'm not mistaking, the StarlingState class in citrus.core.starling is missing...

If this isn't an issue and I'm just being retarded, then please do accept my apologies. ;)

**Comment by alamboley** [comment]
Hey thanks for the nice word!

I'm pretty sure that you're using Flash Builder 4.6, isn't it? It seems there are some issues with it and SWC. Could you use the source code directly? And you will have the last fix ;)

**Comment by kyle1046** [comment]
i am using Flash Builder 4.6
what do you mean?

**Comment by alamboley** [comment]
Don't use the SWC, but the citrus source code instead!
You'll need the lib, src, & srclib folder https://github.com/DaVikingCode/Citrus-Engine#repository-setup
