### ISSUE TITLE
Is it plannig support Starling 2?

### ISSUE THREAD

**Issue by ShockWave2048** [DaVikingCode/Citrus-Engine#279]

**Comment by gsynuh** [comment]
Sure we'll update, just going to wait for some free time to do so, as well as fixes for the current performance issues

**Comment by ShockWave2048** [comment]
Nice news! Thanks for answer!

**Comment by alamboley** [comment]
Yes, there will be a last update on Starling 1.x with Feathers 2.x. They we move everything on Starling 2 ;)

**Comment by MartyWallace** [comment]
I would avoid it for now... I got half way through upgrading my framework to 2.0 and decided to roll back after various problems I was having with it.

**Comment by alamboley** [comment]
The transition has started.
