### ISSUE TITLE
AnimationSequence's bugs

### ISSUE THREAD

**Issue by Jacowaco** [DaVikingCode/Citrus-Engine#281]
First,
I found an error, in AnimationSequence, you have to replace
_mcSequences[animation].smoothing
for
_mcSequences[animation].textureSmoothing
Or it gives an error as the smoothing parameter no longer exists.

Seconds, in my game i use the onAnimationComplete feature to change between animations. It has always worked well in previous CE versions.
But now, there is a (seemingly random) chance that the function you assign to onAnimation complete isn't fired when the animation ends. I haven't found why or when it happens, it is pretty random, most of the time it works well and then it happens and my animation gets stuck in the last frame of the playing animation.
I noticed you changed the original Signal class to a new Signal1 class, so i guess the problem is there.

**Comment by alamboley** [comment]
Thanks, I corrected to `textureSmoothing`.

Wow if the new Signal lib doesn't work correctly, that's a serious issue! Could you add a `trace` to the `_animationComplete` method, to be sure the method is called? It could be a bug on Starling's MovieClip.

**Comment by Jacowaco** [comment]
So i put a trace() inside the "private function _animationComplete(evt:Event):void" of the AnimationSequence class and the trace didn't appear when the bug ocurred. I think it has to do with the new Signal1 class that is being used instead of the old Signal class.

**Comment by alamboley** [comment]
Well if your `trace`in the `_animationComplete`method isn't called, the issue doesn't come from the new Signal lib, but from Starling's MovieClip!

**Comment by Jacowaco** [comment]
Oh, you are right. What can you recommend me to do?

**Comment by alamboley** [comment]
Well I recommend to make a simple small case to reproduce & rise a Starling issue.
