### ISSUE TITLE
Change citrus.utils.Platform isLandscape() from private to public?

### ISSUE THREAD

**Issue by Smurfatron** [DaVikingCode/Citrus-Engine#282]
Not sure if there's a reason it's private, but changing it to public would make it useful when adjusting layouts after device rotation

**Comment by SnkyGames** [comment]
Strange! When I did my pull request in March 2015, I'm pretty sure this was a public function.
Issue Ref: #226 - A couple of lines seem different, but that's alright, I'll take this copy and remember to update it from what CE has currently. Oh.. so many iPhones >< ( 6 SE... 7 soonish )
