### ISSUE TITLE
MediatorScene._poolObjects after scene cycle, has null.

### ISSUE THREAD

**Issue by ShockWave2048** [DaVikingCode/Citrus-Engine#287]
Have simple switch scenes (inherited from StarlingScene), Menu->Level->Menu.
`CitrusEngine.getInstance().scene = new Level;`
After second call new level scene, it's start (playing some tasks before) and crash with _poolObjects refs to null ((

**Comment by gsynuh** [comment]
Can you provide a simple reproducible case?

**Comment by gsynuh** [comment]
I'm closing this issue since we now have the SceneManager and that may have solved it, if it didn't please provide a sample.
