### ISSUE TITLE
Implement a 'remove()' method to PhysicsCollisionCategories.as

### ISSUE THREAD

**Issue by Snky** [DaVikingCode/Citrus-Engine#288]
Why? The limitation of the max number of categories(can the max number be raised?).
With this feature, a scene could load the required categories, and unload them when the scene ends; 
Thus allowing at least fifteen categories minimum per scene rather than per application.

**Comment by gsynuh** [comment]
@Snky  I didn't test it in a state but separately, so it seems all good but let me know if there are any issues :)
