### ISSUE TITLE
ObjectMakerStarling is using old QuadBatch

### ISSUE THREAD

**Issue by oskaraqp** [DaVikingCode/Citrus-Engine#289]
Using the latest starling 2.0.2 I get some errors because this has not been changed to MeshBatch(which looks to be the imrpoved way to replace quadbatch) is there any code to use with the latest Starling version? looks like quadbatch was removed from starling 2.0 beta

**Comment by gadyosef** [comment]
Had the same issue a few days ago.
In the meantime just changed it to use MeshBatch and work OK.

**Comment by oskaraqp** [comment]
Yes, it solved the issue, thanks.

**Comment by alamboley** [comment]
Solved via #291

**Comment by oskaraqp** [comment]
Perfect, thanks.
