### ISSUE TITLE
Jump bug CE 3.1.12 + Nape

### ISSUE THREAD

**Issue by grushan** [DaVikingCode/Citrus-Engine#294]
Hello. 
If your hero jump to the wall and you hold your movement key, the hero will hang on the wall. 
```
override protected function createMaterial():void {

    super.createMaterial();
    _material.staticFriction = 0; //this line added
    _material.elasticity = 0;
}
```
I apply this code for the hero and wall - does not help.
How else can you solve this problem?

Watch video: https://youtu.be/3oD2NR1tF28
Sorry for my bad English.

**Comment by gsynuh** [comment]
Hi @grushan , you should also consider setting a (0) value for _material.dynamicFriction as Hero is dynamic so it should factor in as well.

**Comment by grushan** [comment]
@gsynuh oh, thanks! Its really work!
