### ISSUE TITLE
FluidBox.as needs to be removed

### ISSUE THREAD

**Issue by hewenyuann19930327** [DaVikingCode/Citrus-Engine#301]
Citrus-Engine-master\src\citrus\objects\complex\box2dstarling\FluidBox.as   needs to be deleted.  it's inport things  	import starling.extensions.filters.ThresholdFilter;   has been romoved  so   i got a error!

**Comment by gsynuh** [comment]
Agreed,

In fact there was a discussion about just putting all example objects in a seperate repository so this one is juste "core" code (CitrusObject,CitrusSprite,NapePhysicsObject,Box2DPhysicsObject). Hero and everything else that are example implementations that eventually most people have to extend one day or completely recreate in my opinion should not be under the main citrus package.

( @alamboley  )
